sudo: false
language: ruby
cache: bundler
install: true # skip bundle install for build job
branches:
  except:
    - /^production_release_\d+$/
    - /^staging_release_\d+$/
notifications:
  email: false

matrix:
  include:
    - env: TRAVIS_JOB=build
      sudo: required
      services: docker

script: bash ./script/travis.sh
