apiVersion: v1
kind: ConfigMap
metadata:
  name: interstellar-profile
  labels:
    app: interstellar
data:
  lumos.sh: |-
    PS1="\n[\033[32m\w\033[0m] ==\033[30;47m ${NAMESPACE:-staging}${NODE_NAME:+/$NODE_NAME} \u@[${POD_NAME:-`hostname`}] \033[0m==\n\d \t [\#:\j]$ "
    export PS1

    alias ..='cd ..'
    alias ll='ls -l'
    alias la='ls -la'
